== Classes overview

This project contains 6 classes and 0 interface.

.Classes list
[cols="", %autowidth, frame=all, grid=all, stripes=none]
|===
|Classes |Interfaces

|<<ERROR_Add UUT Error.lvclass>>
|

|<<ERROR_Init.lvclass>>
|

|<<ERROR_Prompt.lvclass>>
|

|<<ERROR_Stop.lvclass>>
|

|<<ERROR_Write.lvclass>>
|

|<<Error.lvclass>>
|
|===

[plantuml, format="svg", align="center"]
....
@startuml
set namespaceSeparator :
skinparam ClassBackgroundColor #FFFFFF
skinparam ClassBorderColor #555555
skinparam ClassFontColor #000000
skinparam ClassHeaderBackgroundColor #808080

skinparam top to bottom direction
class "TSC Error.lvlib:ERROR_Add UUT Error" {
{method} -Execute()

}
"TSC Error.lvlib:Error" <|-- "TSC Error.lvlib:ERROR_Add UUT Error"


class "TSC Error.lvlib:ERROR_Init" {
{method} -Execute()

}
"TSC Error.lvlib:Error" <|-- "TSC Error.lvlib:ERROR_Init"


class "TSC Error.lvlib:ERROR_Prompt" {
{method} -Execute()

}
"TSC Error.lvlib:Error" <|-- "TSC Error.lvlib:ERROR_Prompt"


class "TSC Error.lvlib:ERROR_Stop" {
{method} -Execute()

}
"TSC Error.lvlib:Error" <|-- "TSC Error.lvlib:ERROR_Stop"


class "TSC Error.lvlib:ERROR_Write" {
{method} -Execute()

}
"TSC Error.lvlib:Error" <|-- "TSC Error.lvlib:ERROR_Write"


class "TSC Error.lvlib:Error" {
{field} ~Error : Error Cluster
{field} ~Error Log : Path
{field} ~Update Queue : NoType
{field} ~UUT Errors : Path
{field} ~Application Errors : Path
{field} ~Max File Size : I64
{method} +Execute()

}



@enduml
....
